default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pagecord_dev
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "olly") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

test:
  <<: *default
  database: pagecord_test
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "olly") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
